# renovate-debian: suite=trixie
FROM docker.io/debian:trixie-slim@sha256:a347fd7510ee31a84387619a492ad6c8eb0af2f2682b916ff3e643eb076f925a

# Setup image
RUN apt-get update \
    && apt-get install -y dnsmasq=2.91-1
# COPY config
COPY dnsmasq.conf /etc/dnsmasq.conf
# Creating directory for custom configuration and additional hosts
RUN mkdir -p /etc/dnsmasq.d /etc/dnsmasq_hosts.d
# Set custom entrypoint and command
COPY entrypoint.sh /entrypoint
EXPOSE 53/udp
EXPOSE 67/udp
VOLUME [ "/etc/dnsmasq.d", "/etc/dnsmasq_hosts.d" ]
ENTRYPOINT [ "/entrypoint" ]
CMD [ "dnsmasq" ]
