#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

request = json.load(sys.stdin)

# write dnsmasq configuration to easy json file, will be used by UI
open("config.json", "w").write(json.dumps(request))

agent.run_helper('expand-config').check_returncode()
