#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import agent

# Force the initialization of config.json for get-configuration:
agent.run_helper('expand-config').check_returncode()

open("dns-records.json", "w").write(json.dumps({"records": []}))
