#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent

# parse data and init variables
data = json.load(sys.stdin)
agent_source_id = os.getenv("AGENT_EVENT_SOURCE")
# execute only if traefik is the source of the event and the node_id is the same as the current node
if 'traefik' in agent_source_id and os.environ['NODE_ID'] == str(data['node_id']):
    agent.run_helper("../bin/reload_hosts", agent_source_id)
