#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import network

interfaces = network.list_interfaces()
response = list[dict]()
for interface in interfaces:
    if len(interface['addresses']) > 0:
        response.append({
            "name": interface["name"],
            "network": format(interface['addresses'][0]['network'])
        })

json.dump({
    "data": response
}, sys.stdout)
