#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json

config = json.load(open('config.json'))

if 'gateway' not in config['dhcp-server']:
    # the field is left empty, to avoid assigning a default value
    # this is because if in any case the interface the dhcp-server is running
    # has two or more ips, a default gateway might cause way too many issues
    config['dhcp-server']['gateway'] = ''

json.dump(config, fp=open('config.json', 'w'))
